name: Garage Plug Alarm

on:
  workflow_dispatch:
  schedule:
  - cron: "0 * * * *"  # hourly

jobs:
  job:
    runs-on: ubuntu-latest
    env:
      VESYNC_EMAIL: ${{ secrets.VESYNC_EMAIL }}
      VESYNC_PASSWORD: ${{ secrets.VESYNC_PASSWORD }}
      GMAIL_APP_PASSWORD: ${{ secrets.GMAIL_APP_PASSWORD }}
      GMAIL_ADDRESS: ${{ secrets.GMAIL_ADDRESS }}
      GARAGE_RECIPIENTS: ${{ vars.GARAGE_RECIPIENTS }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          cache: 'pip' # caching pip dependencies
      - run: pip install -r requirements.txt
      - run: python3 app.py alarm
